version: '3'
services:
  django:
    build:
      context: .
      dockerfile: "./docker-compose/django/Dockerfile"
    restart: always
    container_name: gogo_django
  vuejs:
    build: "./frontend"
    ports:
      - "8080:8080"

#
#version : '3'
#services: # docker-compose 에서 컨테이너(service) 단위를 묶음
#  web: # 앱 service 이름zdz
#    build:
#      dockerfile : Dockerfile # 빌드할 Docker 파일 위치
#
#    command: python manage.py runserver 0.0.0.0:8000 # docker-compose up 을 command 창에 입력하면 실행할 명령어
#    volumes: # 로컬 폴더(.k
#  )와 docker 의 /code 폴더를 마운트(연결)
#      - .:/code
#    ports: # docker 와 로컬에서 서로 입력 출력할 포트, 접근할 포트
#      - "8000:8000"dlf
#    env: # docker 내에서 필요한 환경변수 설정
#      - SECRET_KEY='abcabc'
#      - DB_NAME='db'