# Generated by Django 2.2 on 2019-05-17 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=None, max_length=500)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('긴급', '긴급'), ('중요', '중요'), ('보통', '보통')], max_length=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
