# Generated by Django 2.2 on 2019-05-07 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='update_at',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='saw',
        ),
        migrations.AddField(
            model_name='feed',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
