# Generated by Django 2.2 on 2019-05-09 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20190508_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='created_id',
            new_name='creator',
        ),
    ]
