# Generated by Django 2.2 on 2019-05-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_auto_20190510_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
