# Generated by Django 2.2 on 2019-05-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_schedules_created_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedules',
            old_name='created_id',
            new_name='creator',
        ),
    ]
