# Generated by Django 2.2 on 2019-05-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20190510_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
